### ISSUE TITLE
是否可以不依赖EFCore使用？

### ISSUE THREAD

**Issue by Deali-Axy** [MiCake/MiCake#20]
作者你好，我试用了一下该项目，但发现注册服务时需要传入 `DbContext`，我的项目没有使用EFCore，似乎无法接入MiCake？

```c#
services.AddMiCakeWithDefault<MyDbContext, MyEntryModule>()
           .Build();
```

**Comment by uoyoCsharp** [comment]
@Deali-Axy  你好  现在是必须要使用EFCore的。   因为用到了EFCore的一些生命周期钩子。
